version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: login
    ports:
      - "3307:3306"  # เปิดพอร์ตถ้าต้องการ remote access
    volumes:
      - db_data:/var/lib/mysql
      -  ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - backend

volumes:
  db_data:

networks:
  backend:

# phpmyadmin (optional for gui)